export type ReportPageEntry = {
  id: string
  title: string
  pageNumber: number
}

export const pageRegistry: ReportPageEntry[] = [
  { id: "cover", title: "Cover", pageNumber: 1 },
  { id: "nordastro", title: "AstroVela Cream Page", pageNumber: 2 },
  { id: "personalized-cover", title: "Personalized Cover (cream background)", pageNumber: 3 },
  { id: "toc", title: "Table of Contents", pageNumber: 4 },
  { id: "astrology-introduction-5", title: "Astrology Introduction", pageNumber: 5 },
  { id: "sun-sign-replica", title: "Sun Sign", pageNumber: 6 },
  { id: "libra-four-quadrant", title: "Libra Four Quadrant", pageNumber: 7 },
  { id: "moon-sign-replica", title: "Moon Sign", pageNumber: 8 },
  { id: "pisces-content", title: "Pisces Content", pageNumber: 9 },
  { id: "rising-sign-replica", title: "Rising Sign", pageNumber: 10 },
  { id: "sagittarius-content", title: "Sagittarius Content", pageNumber: 11 },
  { id: "mercury-replica", title: "Mercury Planet", pageNumber: 12 },
  { id: "libra-mercury-content", title: "Libra Mercury Content", pageNumber: 13 },
  { id: "venus-replica", title: "Venus Planet", pageNumber: 14 },
  { id: "sagittarius-venus-content", title: "Sagittarius Venus Content", pageNumber: 15 },
  { id: "mars-replica", title: "Mars Planet", pageNumber: 16 },
  { id: "libra-mars-content", title: "Libra Mars Content", pageNumber: 17 },
  { id: "jupiter-replica", title: "Jupiter Planet", pageNumber: 18 },
  { id: "cancer-jupiter-content", title: "Cancer Jupiter Content", pageNumber: 19 },
  { id: "saturn-replica", title: "Saturn Planet", pageNumber: 20 },
  { id: "capricorn-saturn-content", title: "Capricorn Saturn Content", pageNumber: 21 },
  { id: "uranus-replica", title: "Uranus Planet", pageNumber: 22 },
  { id: "capricorn-uranus-content", title: "Capricorn Uranus Content", pageNumber: 23 },
  { id: "neptune-replica", title: "Neptune Planet", pageNumber: 24 },
  { id: "capricorn-neptune-content", title: "Capricorn Neptune Content", pageNumber: 25 },
  { id: "pluto-replica", title: "Pluto Planet", pageNumber: 26 },
  { id: "scorpio-pluto-content", title: "Scorpio Pluto Content", pageNumber: 27 },
  { id: "chiron-replica", title: "Chiron", pageNumber: 28 },
  { id: "cancer-chiron-content", title: "Cancer Chiron Content", pageNumber: 29 },
  { id: "compatibility-wheel", title: "Compatibility Wheel", pageNumber: 30 },
  { id: "compatibility-1", title: "Compatibility Part 1", pageNumber: 31 },
  { id: "compatibility-2", title: "Compatibility Part 2", pageNumber: 32 },
  { id: "compatibility-3", title: "Compatibility Part 3", pageNumber: 33 },
  { id: "guide-to-astrology-title", title: "Guide to Astrology Title", pageNumber: 34 },
  { id: "modern-astrology-intro", title: "Modern Astrology Intro", pageNumber: 35 },
  { id: "history-of-astrology", title: "History of Astrology", pageNumber: 36 },
  { id: "astrology-types", title: "Astrology Types", pageNumber: 37 },
  { id: "modern-astrology-details", title: "Modern Astrology Details", pageNumber: 38 },
  { id: "modern-western-astrology", title: "Modern Western Astrology", pageNumber: 39 },
  { id: "astrology-concepts-replica", title: "Astrology Concepts", pageNumber: 40 },
  { id: "zodiac-signs-overview", title: "Zodiac Signs Overview", pageNumber: 41 },
  { id: "elemental-classification", title: "Elemental Classification", pageNumber: 42 },
  { id: "modalities", title: "Modalities", pageNumber: 43 },
  { id: "duality", title: "Duality", pageNumber: 44 },
  { id: "significance", title: "Significance", pageNumber: 45 },
  { id: "detailed-sign-aries", title: "Detailed Sign Aries", pageNumber: 46 },
  { id: "sign-details-aries", title: "Sign Details Aries", pageNumber: 47 },
  { id: "detailed-sign-taurus", title: "Detailed Sign Taurus", pageNumber: 48 },
  { id: "sign-details-taurus", title: "Sign Details Taurus", pageNumber: 49 },
  { id: "detailed-sign-gemini", title: "Detailed Sign Gemini", pageNumber: 50 },
  { id: "sign-details-gemini", title: "Sign Details Gemini", pageNumber: 51 },
  { id: "detailed-sign-cancer", title: "Detailed Sign Cancer", pageNumber: 52 },
  { id: "sign-details-cancer", title: "Sign Details Cancer", pageNumber: 53 },
  { id: "detailed-sign-leo", title: "Detailed Sign Leo", pageNumber: 54 },
  { id: "sign-details-leo", title: "Sign Details Leo", pageNumber: 55 },
  { id: "detailed-sign-virgo", title: "Detailed Sign Virgo", pageNumber: 56 },
  { id: "sign-details-virgo", title: "Sign Details Virgo", pageNumber: 57 },
  { id: "detailed-sign-libra", title: "Detailed Sign Libra", pageNumber: 58 },
  { id: "sign-details-libra", title: "Sign Details Libra", pageNumber: 59 },
  { id: "detailed-sign-scorpio", title: "Detailed Sign Scorpio", pageNumber: 60 },
  { id: "sign-details-scorpio", title: "Sign Details Scorpio", pageNumber: 61 },
  { id: "detailed-sign-sagittarius", title: "Detailed Sign Sagittarius", pageNumber: 62 },
  { id: "sign-details-sagittarius", title: "Sign Details Sagittarius", pageNumber: 63 },
  { id: "detailed-sign-capricorn", title: "Detailed Sign Capricorn", pageNumber: 64 },
  { id: "sign-details-capricorn", title: "Sign Details Capricorn", pageNumber: 65 },
  { id: "detailed-sign-aquarius", title: "Detailed Sign Aquarius", pageNumber: 66 },
  { id: "sign-details-aquarius", title: "Sign Details Aquarius", pageNumber: 67 },
  { id: "detailed-sign-pisces", title: "Detailed Sign Pisces", pageNumber: 68 },
  { id: "sign-details-pisces", title: "Sign Details Pisces", pageNumber: 69 },
  { id: "solarsystem-70", title: "Solar System", pageNumber: 70 },
  { id: "planetsintroduction-71", title: "The Planets Introduction", pageNumber: 71 },
  { id: "planetssignificance-72", title: "The Significance of Planets", pageNumber: 72 },
  { id: "luminaries-73", title: "The Luminaries", pageNumber: 73 },
  { id: "innerplanets-74", title: "The Inner Planets - Mercury", pageNumber: 74 },
  { id: "venusmars-75", title: "Venus and Mars", pageNumber: 75 },
  { id: "socialplanets-76", title: "The Social Planets", pageNumber: 76 },
  { id: "outerplanets-77", title: "The Outer Planets", pageNumber: 77 },
  { id: "plutochiron-78", title: "Pluto and Chiron", pageNumber: 78 },
  { id: "retrogradues-79", title: "Retrogrades", pageNumber: 79 },
  { id: "mercuryretrograde-80", title: "Mercury Retrograde", pageNumber: 80 },
  { id: "mercuryretrogradecontinued-81", title: "Mercury Retrograde Continued", pageNumber: 81 },
  { id: "venusretrograde-82", title: "Venus Retrograde", pageNumber: 82 },
  { id: "venusretrogradecontinued-83", title: "Venus Retrograde Continued", pageNumber: 83 },
  { id: "marsretrograde-84", title: "Mars Retrograde", pageNumber: 84 },
  { id: "marsretrogradecontinued-85", title: "Mars Retrograde Continued", pageNumber: 85 },
  { id: "jupiterretrograde-86", title: "Jupiter Retrograde", pageNumber: 86 },
  { id: "jupiterretrogradecontinued-87", title: "Jupiter Retrograde Continued", pageNumber: 87 },
  { id: "saturnretrograde-88", title: "Saturn Retrograde", pageNumber: 88 },
  { id: "saturnretrogradecontinued-89", title: "Saturn Retrograde Continued", pageNumber: 89 },
  { id: "uranusretrograde-90", title: "Uranus Retrograde", pageNumber: 90 },
  { id: "uranusretrogradecontinued-91", title: "Uranus Retrograde Continued", pageNumber: 91 },
  { id: "neptuneretrograde-92", title: "Neptune Retrograde", pageNumber: 92 },
  { id: "neptuneretrogradecontinued-93", title: "Neptune Retrograde Continued", pageNumber: 93 },
  { id: "plutoretrograde-94", title: "Pluto Retrograde", pageNumber: 94 },
  { id: "plutoretrogradecontinued-95", title: "Pluto Retrograde Continued", pageNumber: 95 },
  { id: "chironretrograde-96", title: "Chiron Retrograde", pageNumber: 96 },
  { id: "chironretrogradecontinued-97", title: "Chiron Retrograde Continued", pageNumber: 97 },
  { id: "housesintroduction-98", title: "Houses Introduction", pageNumber: 98 },
  { id: "twelvehousesoverview-99", title: "Houses 1-4", pageNumber: 99 },
  { id: "houses-5-8-100", title: "Houses 5-8", pageNumber: 100 },
  { id: "houses-9-12-101", title: "Houses 9-12", pageNumber: 101 },
  { id: "divination-astrology-title-102", title: "Divination & Astrology Title", pageNumber: 102 },
  { id: "how-to-interpret-horoscopes-103", title: "How to Interpret Horoscope Predictions", pageNumber: 103 },
  { id: "the-major-angles-104", title: "The Major Angles", pageNumber: 104 },
  { id: "interpreting-daily-horoscopes-105", title: "Interpreting Daily, Weekly, and Monthly Horoscopes", pageNumber: 105 },
  { id: "advanced-techniques-106", title: "Advanced Techniques for a Deeper Understanding", pageNumber: 106 },
  { id: "crystalfoundations-107", title: "Crystal Foundations", pageNumber: 107 },
  { id: "crystals-in-astrology-108", title: "Crystals in Astrology", pageNumber: 108 },
  { id: "history-crystals-astrology-109", title: "History of Crystals and Astrology", pageNumber: 109 },
  { id: "crystalhistory-111", title: "Crystal History", pageNumber: 110 },
  { id: "z-112", title: "Zodiac Crystals 1-4", pageNumber: 111 },
  { id: "z-113", title: "Zodiac Crystals 5-8", pageNumber: 112 },
  { id: "z-114", title: "Zodiac Crystals 9-12", pageNumber: 113 },
  { id: "personalizedcrystalcharts-115", title: "Personalized Crystal Charts", pageNumber: 114 },
  { id: "crystalcleansingguide-116", title: "Crystal Cleansing Guide", pageNumber: 115 },
  { id: "crystalcaresteps-117", title: "Crystal Care Steps", pageNumber: 116 },
  { id: "astrologicalritualsmeditations-118", title: "Astrological Rituals & Meditations", pageNumber: 117 },
  { id: "astrologicalcrystalelixirs-119", title: "Astrological Crystal Elixirs", pageNumber: 118 },
  { id: "chooseastrologicaltiming-119", title: "Choose Astrological Timing", pageNumber: 119 },
  { id: "planetaryseasonaltiming-120", title: "Planetary & Seasonal Timing", pageNumber: 120 },
  { id: "astrologicalevents-121", title: "Astrological Events & Elixirs", pageNumber: 121 },
  { id: "agatemarbletexture-122", title: "Agate Marble Texture", pageNumber: 122 },
  { id: "palmistryhandmodel-123", title: "Palmistry Hand Model", pageNumber: 123 },
  { id: "palmistrymysteriesintro-125", title: "The Mysteries of Palmistry", pageNumber: 125 },
  { id: "palmistryhistorypage-126", title: "The History of Palmistry", pageNumber: 126 },
  { id: "understandingpalmtypes-127", title: "Understanding the Palm - Four Types", pageNumber: 127 },
  { id: "themountspage-128", title: "The Mounts", pageNumber: 128 },
  { id: "findingmountssteps-129", title: "Finding Mounts Steps", pageNumber: 129 },
  { id: "majorlinespage-130", title: "The Major Lines", pageNumber: 130 },
  { id: "palmistrydetailspage-131", title: "Palmistry Details", pageNumber: 131 },
  { id: "tarotreadingphoto-132", title: "Tarot Reading Photo", pageNumber: 132 },
  { id: "tarotcardsintro-133", title: "Tarot Cards Intro", pageNumber: 133 },
  { id: "majorarcanastructure-134", title: "Major Arcana Structure", pageNumber: 134 },
  { id: "majorarcanacards1-135", title: "Major Arcana Cards 1", pageNumber: 135 },
  { id: "majorarcanacards2-136", title: "Major Arcana Cards 2", pageNumber: 136 },
  { id: "uprightreversedcards-137", title: "Upright/Reversed Cards", pageNumber: 137 },
  { id: "minorarcanasuits-138", title: "Minor Arcana Suits", pageNumber: 138 },
  { id: "conductingreadingsteps-139", title: "Conducting Reading Steps", pageNumber: 139 },
  { id: "populartarotspreads-140", title: "Popular Tarot Spreads", pageNumber: 140 },
  { id: "celticcrossspread-141", title: "Celtic Cross Spread", pageNumber: 141 },
  { id: "lovespreadlayout-142", title: "Love Spread Layout", pageNumber: 142 },
  { id: "yesnospread-143", title: "Yes/No Spread", pageNumber: 143 },
  { id: "interpretingtarottips-144", title: "Interpreting Tarot Tips", pageNumber: 144 },
  { id: "tarotsuperstitions-145", title: "Tarot Superstitions", pageNumber: 145 },
  { id: "numerologymandalareplica-146", title: "Numerology Mandala", pageNumber: 146 },
  { id: "numerologyintroreplica-147", title: "Numerology Introduction", pageNumber: 147 },
  { id: "numerologycorenumbersreplica-148", title: "Numerology Core Numbers", pageNumber: 148 },
  { id: "numerologyeverydaylifereplica-149", title: "Numerology Everyday Life", pageNumber: 149 },
  { id: "meaningofnumbers14replica-150", title: "Meaning of Numbers 1-4", pageNumber: 150 },
  { id: "meaningofnumbers59replica-151", title: "Meaning of Numbers 5-9", pageNumber: 151 },
  { id: "lovepotionphoto-152", title: "Love Potion Photo", pageNumber: 152 },
  { id: "loverelationshipsintroreplica-153", title: "Love & Relationships Introduction", pageNumber: 153 },
  { id: "astrologyrelationshiptimingreplica-154", title: "Astrology & Relationship Timing", pageNumber: 154 },
  { id: "astrologicaltimingdetailsreplica-155", title: "Astrological Timing Details", pageNumber: 155 },
  { id: "crystalsforloveintroreplica-156", title: "Crystals for Love Introduction", pageNumber: 156 },
  { id: "lovecrystalscollectionreplica-157", title: "Love Crystals Collection", pageNumber: 157 },
  { id: "fengshuiromanticprosperityreplica-158", title: "Feng Shui for Romantic Prosperity", pageNumber: 158 },
  { id: "fengshuilovetipsreplica-159", title: "Feng Shui Love Tips", pageNumber: 159 },
  { id: "loveaffirmationsmantrasreplica-160", title: "Love Affirmations & Mantras", pageNumber: 160 },
  { id: "mantrasattractmaintainlovereplica-161", title: "Mantras to Attract & Maintain Love", pageNumber: 161 },
  { id: "lovespellsritualsintroreplica-162", title: "Love Spells & Rituals Introduction", pageNumber: 162 },
  { id: "spellsforattractinglovereplica-163", title: "Spells for Attracting Love", pageNumber: 163 },
  { id: "ritualsstrengthenrelationshipsreplica-164", title: "Rituals to Strengthen Relationships", pageNumber: 164 },
  { id: "cosmiccouplestarrysky-165", title: "Cosmic Couple Starry Sky", pageNumber: 165 },
  { id: "cosmicnebulaspace-166", title: "Cosmic Nebula Space", pageNumber: 166 },
  { id: "astrologerlexicontitlereplica-167", title: "ASTROLOGER'S LEXICON Title", pageNumber: 167 },
  { id: "glossaryacreplica-168", title: "Glossary A-C", pageNumber: 168 },
  { id: "glossaryejreplica-169", title: "Glossary E-J", pageNumber: 169 },
  { id: "glossarykqreplica-170", title: "Glossary K-Q", pageNumber: 170 },
  { id: "glossaryrzreplica-171", title: "Glossary R-Z", pageNumber: 171 },
  { id: "astrologicaleventsintroreplica-172", title: "ASTROLOGICAL EVENTS Introduction", pageNumber: 172 },
  { id: "calendar2025part1-173", title: "2025 Calendar Part 1", pageNumber: 173 },
  { id: "calendar2025part2-174", title: "2025 Calendar Part 2", pageNumber: 174 },
  { id: "planetaryretrogrades2025replica-175", title: "2025 Planetary Retrogrades", pageNumber: 175 },
  { id: "year2026photoreplica-176", title: "2026 Year Photo", pageNumber: 176 },
  { id: "calendar2026part1-177", title: "2026 Calendar Part 1", pageNumber: 177 },
  { id: "calendar2026part2-178", title: "2026 Calendar Part 2", pageNumber: 178 },
  { id: "planetaryretrogrades2026replica-179", title: "2026 Planetary Retrogrades", pageNumber: 179 },
  { id: "year2027photoreplica-180", title: "2027 Year Photo", pageNumber: 180 },
  { id: "calendar2027part1-181", title: "2027 Calendar Part 1", pageNumber: 181 },
  { id: "calendar2027part2-182", title: "2027 Calendar Part 2", pageNumber: 182 },
  { id: "year2028photoreplica-183", title: "2028 Year Photo - NEW", pageNumber: 183 },
  { id: "calendar2028part1-184", title: "2028 Calendar Part 1", pageNumber: 184 },
  { id: "calendar2028part2-185", title: "2028 Calendar Part 2", pageNumber: 185 },
  { id: "planetaryretrogrades2027replica-186", title: "2027 Planetary Retrogrades", pageNumber: 186 },
  { id: "planetaryretrogrades2028replica-187", title: "2028 Planetary Retrogrades", pageNumber: 187 },
  { id: "year2029photoreplica-188", title: "2029 Year Photo", pageNumber: 188 },
  { id: "calendar2029part1-189", title: "2029 Calendar Part 1", pageNumber: 189 },
  { id: "calendar2029part2-190", title: "2029 Calendar Part 2", pageNumber: 190 },
  { id: "planetaryretrogrades2029replica-191", title: "2029 Planetary Retrogrades", pageNumber: 191 },
  { id: "countrysidemilkywayreplica-192", title: "Countryside Milky Way", pageNumber: 192 },
  { id: "finalwordstitlereplica-193", title: "Final Words Title", pageNumber: 193 },
  { id: "finalconclusionreplica-194", title: "Final Conclusion", pageNumber: 194 },
  { id: "minimalisthandillustrationreplica-195", title: "Minimalist Hand Illustration", pageNumber: 195 },
  { id: "personalizedmessagereplica-196", title: "Personalized Message - Back Cover", pageNumber: 196 },
]
